# Generated by Django 5.2.6 on 2025-09-17 21:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Mood', max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Select the date for this mood')),
                ('mood_type', models.CharField(choices=[('depressed', 'Depressed'), ('sad', 'Sad'), ('okay', 'Okay'), ('good', 'Good'), ('happy', 'Happy'), ('ecstatic', 'Ecstatic'), ('irritated', 'Irritated'), ('mad', 'Mad'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('calm', 'Calm'), ('confused', 'Confused'), ('grateful', 'Grateful'), ('lonely', 'Lonely'), ('content', 'Content'), ('overwhelmed', 'Overwhelmed'), ('peaceful', 'Peaceful'), ('energetic', 'Energetic'), ('bored', 'Bored'), ('proud', 'Proud')], default='happy', help_text='Select your current mood', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
